import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { SessionProvider } from "next-auth/react"

import "./globals.css";
import "easymde/dist/easymde.min.css";
import { Toaster } from "sonner";
import { writeClient } from "@/sanity/lib/write-client";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // writeClient.delete({query: `*[_type == "startup" && _id == 'm6nSyVU6lqC08JIvifCa2V' ][0]`})
  return (
    <html lang="en">
      <SessionProvider>
      <body
        className={`${workSans.variable}} antialiased`}
      >
        {children}
        <Toaster richColors/>
      </body>
      </SessionProvider>
    </html>
  );
}
